services:
  # 后端服务基础配置
  backend-base:
    build:
      context: ../backend
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # 前端服务基础配置
  frontend-base:
    build:
      context: ../frontend
    networks:
      - app-network

  # 数据库服务基础配置
  db-base:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data: 