version: '3.8'

# 此文件扩展基础配置文件
services:
  backend:
    extends:
      file: base.yml
      service: backend-base
    build:
      target: development
    volumes:
      - ../backend:/app
      - /app/venv
      - /app/__pycache__
    ports:
      - "8000:8000"
    env_file:
      - ../backend/.env
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/house_keeper
      - BACKEND_CORS_ORIGINS=["http://localhost:3000", "http://frontend:3000"]
      - PYTHONPATH=/app
    depends_on:
      - db
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    extends:
      file: base.yml
      service: frontend-base
    build:
      dockerfile: Dockerfile
    volumes:
      - ../frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    env_file:
      - ../frontend/.env
    environment:
      - NODE_ENV=development
      - REACT_APP_API_URL=http://localhost:8000/api/v1
    depends_on:
      - backend
    command: npm start
    restart: unless-stopped

  db:
    extends:
      file: base.yml
      service: db-base
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=house_keeper
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    depends_on:
      - db
    networks:
      - app-network 