services:
  test-db:
    extends:
      file: base.yml
      service: db-base
    volumes:
      - test_postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=test_user
      - POSTGRES_PASSWORD=test_password
      - POSTGRES_DB=test_house_keeper
    ports:
      - "5433:5432"  # 使用不同的端口避免与主数据库冲突
    networks:
      - test-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test_user -d test_house_keeper"]

  backend-test:
    build:
      context: ../backend
      target: development
    volumes:
      - ../backend:/app
      - /app/venv
      - /app/__pycache__
    environment:
      - DATABASE_URL=postgresql://test_user:test_password@test-db:5432/test_house_keeper
      - TEST_DATABASE_URL=postgresql://test_user:test_password@test-db:5432/test_house_keeper
      - PYTHONPATH=/app
      - TESTING=True
    depends_on:
      test-db:
        condition: service_healthy
    networks:
      - test-network
    command: pytest -xvs

networks:
  test-network:
    driver: bridge

volumes:
  test_postgres_data: 