name: 测试

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v3
      
      - name: 设置Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true  # 自动安装最新版Docker CLI和Buildx插件
      
      - name: 验证Docker Compose版本
        run: docker compose version
      
      - name: 设置测试环境变量
        run: |
          cp backend/.env.example backend/.env
          cp frontend/.env.development frontend/.env
      
      - name: 构建Docker容器
        run: docker compose up -d
      
      - name: 等待服务启动
        run: |
          echo "等待服务启动..."
          sleep 30
      
      - name: 运行后端测试
        run: docker compose exec -T backend pytest
      
      - name: 运行前端测试
        run: docker compose exec -T frontend npm test -- --watchAll=false
      
      - name: 停止容器
        run: docker compose down 